config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pokemons#index"

  resources 'pokemons', only: %i[index show], param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon
  attr_reader   :height,
                :is_default,
                :weight,
                :moves,
                :types,
                :name,
                :attributes,
                :id,
                :image

  def initialize(query)
    # we pass a query instead of name bc you can create one with its id

    @attributes = ::PokeApiConsumer.new("/pokemon/#{query}").call || {}
    @id = attributes['id']
    @name = attributes['name']
    @height = attributes['height']
    @is_default = attributes['is_default']
    @weight = attributes['weight']
    @types = build_types
    @moves = find_moves
    @image = find_image
  end

  def build_types
    return {} unless attributes['types']

    attributes['types'].map { |type| type['type']['name'] }.map { |name| ::Type.new(name) }
  end

  def find_moves
    return {} unless attributes['moves']

    attributes['moves'].map { |data| data.dig('move', 'name') }
  end

  def find_image
    return {} unless attributes['sprites']

    attributes['sprites']['front_default'] || attributes['sprites'].select { |_, v| v.present? }.first
  end
end

app/models/type.rb
class Type
  attr_reader   :name,
                :damage_to,
                :damage_from,
                :moves,
                :attributes

  def initialize(query)
    @attributes = ::PokeApiConsumer.new("/type/#{query}").call || {}
    @name = attributes["name"]
    @damage_to = find_damaged_to
    @damage_from = find_damaged_from
    @moves = find_moves
  end

  def find_damaged_to
    return {} unless attributes["damage_relations"]

    damaged_types = attributes["damage_relations"].select { |relation| relation.in?(["double_damage_to", "half_damage_to", "no_damage_to"])}
    return {} unless damaged_types

    names_of_damage_types(damaged_types)
  end

  def find_damaged_from
    return {} unless attributes["damage_relations"]

    damaged_types = attributes["damage_relations"].select { |relation| relation.in?(["double_damage_from", "half_damage_from", "no_damage_from"])}
    return {} unless damaged_types

    names_of_damage_types(damaged_types)
  end

  def names_of_damage_types(damage_types)
    damage_types.transform_values { |type| type.pluck("name") }
  end

  def find_moves
    attributes["moves"].pluck("name")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
# frozen_string_literal: true

class PokemonsController < ApplicationController
  def index
    @offset = params[:offset].nil? ? '0' : params[:offset]
    response = ::PokeApiConsumer.new("/pokemon?offset=#{@offset}&limit=20").call
    results = response['results']

    @pokemons = results.pluck('name').map do |name|
      ::Pokemon.new(name)
    end
    @next_page = response['next']
    @previous_page = response['previous']
  end

  def show
    name = params[:pokemon].present? ? params[:pokemon][:name] : params[:name]
    @pokemon = ::Pokemon.new(name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  URL = 'https://pokeapi.co/api/v2'
end

app/helpers/pokemons_helper.rb
# frozen_string_literal: true

module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokepage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Press+Start+2P&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="navbar">
      <div class="navbar-title">
        <h1>
          <%= link_to "PokéWrapper", pokemons_path %>
        </h1>
      </div>
      <div class="navbar-search">
        <%= simple_form_for :pokemon, url: pokemon_url(:name), method: :get, class:"simple_form search"  do |f| %>
          <div class="search-form-control form-group">
            <%= f.input :name, label: false, input_html: { class: "form-control string required", id: "search_query" } %>
            <button name="button" type="submit" class="btn search-btn">
              <i class="fas fa-search"></i> Search
            </button>
          </div>
        <% end %>
      </div>
    </div>
    <div class="content-wrapper">
      <%= yield %>
    </div>

    <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/Myriamdelbreil/pokepage"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> in Palet Town
      </div>
    </div>
  </body>
</html>

app/views/pokemons/index.html.erb
<div class="navigation-buttons">
  <% if @previous_page.present? %>
    <%= link_to "Previous page", pokemons_path(offset: @offset.to_i - 20) %>
  <% end %>
  <% if @next_page.present? %>
    <%= link_to "Next page", pokemons_path(offset: @offset.to_i + 20)%>
  <% end %>
</div>

<div class= "card-grid">
  <%@pokemons.each do |pokemon|%>
    <div class="card-product">
      <%=image_tag(pokemon.image) %>
      <div class="card-product-infos">
        <div class="card-product-column">
          <h2><%= pokemon.name.capitalize %></h2>
          <p>id: <%= pokemon.id %></p>
          <p>types:
            <% types_names = [] %>
            <%= pokemon.types.map { |type| type.name }.join(', ')%></p>
        </div>
        <div class="card-product-column button-div">
          <%= link_to "find more", pokemon_path(name: pokemon.name), class: "btn card-product-button" %>
        </div>
      </div>
    </div>
  <%end%>
</div>

<div class="navigation-buttons">
  <% if @previous_page.present? %>
    <%= link_to "Previous page", pokemons_path(offset: @offset.to_i - 20) %>
  <% end %>
  <% if @next_page.present? %>
    <%= link_to "Next page", pokemons_path(offset: @offset.to_i + 20)%>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<div class="navigation-buttons">
  <%= link_to "Go back to list", pokemons_path %>
</div>

<div class="show">
  <% if @pokemon.name.blank? %>
    <h1>No pokemon found with name <%= params[:name] %>!</h1>
  <% else %>
    <h1><%= @pokemon.name.capitalize %></h1>
    <div style="display: flex; justify-content: center">
      <div class="show-card">
        <h3 class="show-card-title">
          Main attributes
        </h3>
        <div class="show-card-attributes">
          <%=image_tag(@pokemon.image) %>
          <ul>
            <li>id: <%= @pokemon.id %> </li>
            <li>height: <%= @pokemon.height %></li>
            <li>weight: <%= @pokemon.weight %></li>
            <li>default in Pokeworld: <%= @pokemon.is_default %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="show-grid">
      <% @pokemon.types.each do |type| %>
        <div class="show-card">
          <h3 class="show-card-title"><%= type.name.capitalize %></h3>
          <div class="show-card-attributes">
            <div class="show-list-attributes">
              <h4>Damage to:</h4>
              <% damage_to = type.damage_to %>
              <ul>
                <% damage_to.each do |k, v| %>
                  <li><%= "#{k.humanize}: #{v.join(', ')}" %></li>
                <% end %>
              </ul>
            </div>
            <div class="show-list-attributes">
              <h4>Damage from:</h4>
              <% damage_from = type.damage_from %>
              <ul>
                <% damage_from.each do |k, v| %>
                  <% v = v.blank? ? "no pokemon" : v.join(', ') %>
                  <li><%= "#{k.humanize}: #{v}" %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  <% end %>
</div>